### PR TITLE
fix: inconsistent glow

### LINKED ISSUE #5: Consistent glows
As a spectator it seems random on who gets the golden, silver and bronze glow when multiple teams have the same amount of rounds.
Right now it's decided on index. This results in teams with lower indexes stealing the glow from a team in front even though they have the same amount of laps.

In the example it happens to VLK and Home Konvent

https://github.com/user-attachments/assets/965e92d7-7202-47bf-aae2-f8b5d7de5280
 

This is particularly relevant in the opening stages of the race.

### PR DESCRIPTION
**Pull request by Topvennie**
Closes #5

### CODE REVIEW

File: src/components/RunningTrackComponent.vue [hunk 1]
```diff
@@ -199,7 +199,12 @@ export default defineComponent({
       }
     },
     sortedDrawingOrder(teams: Array<Team> | undefined) {
-      return [...teams || []].sort((a, b) => a.rounds - b.rounds);
+      return [...teams || []].sort((a, b) => {
+        const diff = a.rounds - b.rounds
+        if (diff !== 0) return diff;
+
+        return a.updatedAt - b.updatedAt;
```
Comment (smessie) [inline src/components/RunningTrackComponent.vue]: Wouldn't it make more sense to compare the progress [over the current round] if they have the same amount of rounds?

File: src/components/RunningTrackComponent.vue [hunk 2]
```diff
@@ -199,7 +199,12 @@ export default defineComponent({
...
+      });
```
Comment (smessie) [inline src/components/RunningTrackComponent.vue]: `progress` is number between 0 and 1, so we can just sum it with the current rounds.
```suggestion
      return [...teams || []].sort((a, b) => (a.rounds + a.progress) - (b.rounds + b.progress));
```

File: src/components/RunningTrackComponent.vue (hunk 1 above)
Comment (Topvennie) [reply src/components/RunningTrackComponent.vue]: Yeah definitely

**Review by smessie — APPROVED** [review]
LGTM. Thanks!
